name: Deploy to EC2

on:
  push:
    branches:
      - prod

jobs:

  static-analysis:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  deploy:
    runs-on: ubuntu-latest
    needs: static-analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd kmz-manager
            git pull origin prod
            source venv/bin/activate
            pip install -r requirements.txt
            sudo supervisorctl restart kmz_manager
          EOF

  run-nettacker:
    name: Run Nettacker
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install nettacker

      - name: Run Nettacker Command
        run: |
          source venv/bin/activate
          nettacker -i ${{ secrets.EC2_HOST }} --profile scan --ports 80