name: Deploy to EC2

on:
  push:
    branches:
      - prod

jobs:

  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Static Security Analysis with SonarQube
      uses: sonarsource/sonarcloud-github-action@v1.5
      with:
        args: >
          -Dsonar.projectKey=kmz-manager
          -Dsonar.organization=lucasmvasc
          -Dsonar.sources=.
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd kmz-manager
            git pull origin prod
            source venv/bin/activate
            pip install -r requirements.txt
            sudo supervisorctl restart kmz_manager
          EOF